#include "cc_misc.h"
#include "cc_dict.h"
#include "parser.h"
#include <assert.h>

extern int lineCounter; /* lineCounter is declared in scanner.c, 
						which is generated by flex. */

extern comp_dict_t symbols_table; /* the compiler's symbols table, declared
								  in cc_dict.c */

int getLineNumber(void) 
{
	return lineCounter;
}

void yyerror (char const *mensagem)
{
	int line = getLineNumber();
  	fprintf (stderr, "%s\n in line %d", mensagem, line); 
}

void main_init (int argc, char **argv)
{
  //implemente esta função com rotinas de inicialização, se necessário
}

void main_finalize(void) {
	symbols_table_finalize(&symbols_table);
}

int recognize_token(const char* token_text, int token_id) {

	/* add the token to symbols table only if it is a literal or an
	 * identificator. */
	if (token_id == TK_IDENTIFICADOR || token_id == TK_LIT_FALSE
		|| token_id == TK_LIT_TRUE || token_id == TK_LIT_INT
		|| token_id == TK_LIT_FLOAT || token_id == TK_LIT_CHAR
		|| token_id == TK_LIT_STRING) {

		/* remove double and single quotes if token is a string or 
		 * char literal */
		if (token_id == TK_LIT_STRING || token_id == TK_LIT_CHAR) {			
			assert(token_text[0] == '"' || token_text[0] == '\'');
			char* tmp = (char*)	malloc((strlen(token_text) + 1) * sizeof(char));
			strcpy(tmp, token_text + 1);
			tmp[strlen(tmp) - 1] = '\0';
			token_text = tmp;
		}

		/* add the token to the symbols table. */
		symbols_table_add(token_text, getLineNumber(), &symbols_table);

		if (token_id == TK_LIT_STRING || token_id == TK_LIT_CHAR)
			free((void*)token_text);
	}

	/* then, return the token's identifier. */
	return token_id;
}
