#!/bin/bash
if [[ 2 != $# || ! -f $1 || ! -f $2 ]]; then
	echo "Usage: $0 COMPILER INPUT"
	exit 1
fi
expected=`./tests/scripts/iks2c $2 | gcc -x c - > /dev/null && ./a.out`
output=`"$1" < $2 | ./tests/scripts/ilocsim 2>&1 > /dev/null`
retval=$?
rm a.out
if [[ 0 -eq $retval && $(grep "\ $expected\$" <<< "$output") ]]; then
	exit 0
else
	exit 1
fi
